import type { Analysis, GoalieAssignment, LegacyGoalie } from './model';

/** SQL Server caps a VALUES list at 1000 rows. */
const CHUNK = 500;

const str = (value: string | null): string => (value === null ? 'NULL' : `N'${value.replace(/'/g, "''")}'`);

const chunked = <T>(items: T[]): T[][] => {
  const chunks: T[][] = [];
  for (let index = 0; index < items.length; index += CHUNK) chunks.push(items.slice(index, index + CHUNK));
  return chunks;
};

const insertValues = <T>(table: string, columns: string, items: T[], row: (_item: T) => string): string =>
  chunked(items)
    .map((chunk) => `INSERT INTO ${table} (${columns}) VALUES\n${chunk.map((item) => `    (${row(item)})`).join(',\n')};`)
    .join('\n');

const header = (title: string, notes: string[]): string =>
  [
    `-- ${title}`,
    `-- Generated by \`yarn goalie-backfill:generate\` on ${new Date().toISOString()}.`,
    ...notes.map((note) => `-- ${note}`),
    '-- Idempotent: safe to re-run. Review the verification output, then run COMMIT (or ROLLBACK).',
    '',
    'SET XACT_ABORT ON;',
    'BEGIN TRAN;',
    '',
  ].join('\n');

const FOOTER = ['', '-- COMMIT;', '-- ROLLBACK;', ''].join('\n');

/** D7 legacy stubs, matched on their deterministic email so re-runs never duplicate them. */
export const createLegacyGoaliesSql = (analysis: Analysis): string => {
  const byEmail = new Map<string, LegacyGoalie>();
  for (const row of analysis.names) {
    const { legacy } = row.resolution;
    if (row.resolution.action === 'CREATE' && legacy) byEmail.set(legacy.Email, legacy);
  }
  const legacy = [...byEmail.values()].sort((a, b) => a.Email.localeCompare(b.Email));

  return [
    header('01 — Create legacy goalie stub users (D7)', [
      'Active = 0, NotificationPreference = None, PositionPreference = Goalie, PasswordHash = NULL,',
      'email/username legacy.goalie.<first>.<last>@hockeypickup.invalid (reserved TLD: never deliverable).',
    ]),
    "SELECT COUNT(*) AS LegacyGoaliesBefore FROM AspNetUsers WHERE Email LIKE N'legacy.goalie.%@hockeypickup.invalid';",
    '',
    'DECLARE @Legacy TABLE (FirstName nvarchar(256) NOT NULL, LastName nvarchar(256) NOT NULL, Email nvarchar(256) NOT NULL PRIMARY KEY);',
    legacy.length > 0
      ? insertValues('@Legacy', 'FirstName, LastName, Email', legacy, (g) => `${str(g.FirstName)}, ${str(g.LastName)}, ${str(g.Email)}`)
      : '-- No legacy goalies to create.',
    '',
    'INSERT INTO AspNetUsers (Id, Email, EmailConfirmed, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, AccessFailedCount,',
    '                         UserName, PasswordHash, SecurityStamp, FirstName, LastName, NotificationPreference, PositionPreference,',
    '                         Active, NormalizedEmail, NormalizedUserName, DateCreated)',
    'SELECT LOWER(CONVERT(nvarchar(128), NEWID())), l.Email, 0, 0, 0, 1, 0,',
    '       l.Email, NULL, CONVERT(nvarchar(128), NEWID()), l.FirstName, l.LastName, 0, 3,',
    '       0, UPPER(l.Email), UPPER(l.Email), GETUTCDATE()',
    'FROM @Legacy l',
    'WHERE NOT EXISTS (SELECT 1 FROM AspNetUsers u WHERE u.NormalizedEmail = UPPER(l.Email));',
    '',
    "SELECT COUNT(*) AS LegacyGoaliesAfter FROM AspNetUsers WHERE Email LIKE N'legacy.goalie.%@hockeypickup.invalid';",
    'SELECT u.Id, u.FirstName, u.LastName, u.Email, u.Active, u.NotificationPreference, u.PositionPreference, u.DateCreated',
    'FROM AspNetUsers u JOIN @Legacy l ON u.NormalizedEmail = UPPER(l.Email)',
    'ORDER BY u.LastName, u.FirstName;',
    FOOTER,
  ].join('\n');
};

const assignmentRow = (g: GoalieAssignment): string =>
  `${g.sessionId}, ${str(g.userId)}, ${str(g.legacyEmail)}, ${str(g.displayName)}`;

/** Goalie roster rows (Position = Goalie, TBD team, playing, no BuySell) plus the "convert" updates. */
export const insertGoalieRostersSql = (analysis: Analysis): string => {
  const assignments = analysis.sessions.flatMap((row) => row.assignments);
  const conversions = analysis.sessions.flatMap((row) => row.conversions);
  const columns = 'SessionId, UserId, LegacyEmail, DisplayName';

  return [
    header('02 — Insert goalie roster rows', [
      'Run 01_create_legacy_goalies.sql (and COMMIT it) first: legacy stubs are resolved here by email.',
      'Writes one ActivityLog line per row added or converted (unattributed system action).',
    ]),
    'SELECT COUNT(*) AS GoalieRowsBefore FROM SessionRosters WHERE Position = 3;',
    '',
    'DECLARE @Goalies TABLE (SessionId int NOT NULL, UserId nvarchar(128) NULL, LegacyEmail nvarchar(256) NULL, DisplayName nvarchar(512) NOT NULL);',
    'DECLARE @Convert TABLE (SessionId int NOT NULL, UserId nvarchar(128) NULL, LegacyEmail nvarchar(256) NULL, DisplayName nvarchar(512) NOT NULL);',
    'DECLARE @Inserted TABLE (SessionId int NOT NULL, UserId nvarchar(128) NOT NULL);',
    'DECLARE @Converted TABLE (SessionId int NOT NULL, UserId nvarchar(128) NOT NULL);',
    '',
    assignments.length > 0 ? insertValues('@Goalies', columns, assignments, assignmentRow) : '-- No goalie rows to insert.',
    conversions.length > 0 ? insertValues('@Convert', columns, conversions, assignmentRow) : '-- No skater rows to convert.',
    '',
    '-- Resolve legacy stubs by their deterministic email',
    'UPDATE g SET UserId = u.Id FROM @Goalies g JOIN AspNetUsers u ON u.NormalizedEmail = UPPER(g.LegacyEmail) WHERE g.UserId IS NULL;',
    'IF EXISTS (SELECT 1 FROM @Goalies WHERE UserId IS NULL)',
    'BEGIN',
    '    SELECT * FROM @Goalies WHERE UserId IS NULL;',
    "    THROW 50001, 'Legacy goalie stubs are missing: run and COMMIT 01_create_legacy_goalies.sql first.', 1;",
    'END',
    '',
    'INSERT INTO SessionRosters (SessionId, UserId, TeamAssignment, IsPlaying, IsRegular, JoinedDateTime, LastBuySellId, Position)',
    'OUTPUT inserted.SessionId, inserted.UserId INTO @Inserted',
    'SELECT DISTINCT g.SessionId, g.UserId, 0, 1, 0, s.CreateDateTime, NULL, 3',
    'FROM @Goalies g JOIN Sessions s ON s.SessionId = g.SessionId',
    'WHERE NOT EXISTS (SELECT 1 FROM SessionRosters sr WHERE sr.SessionId = g.SessionId AND sr.UserId = g.UserId);',
    '',
    'UPDATE sr SET Position = 3, TeamAssignment = 0',
    'OUTPUT inserted.SessionId, inserted.UserId INTO @Converted',
    'FROM SessionRosters sr JOIN @Convert c ON c.SessionId = sr.SessionId AND c.UserId = sr.UserId',
    'WHERE NOT (sr.Position = 3 AND sr.TeamAssignment = 0);',
    '',
    'INSERT INTO ActivityLogs (SessionId, UserId, CreateDateTime, Activity)',
    "SELECT i.SessionId, NULL, GETUTCDATE(), CONCAT(u.FirstName, N' ', u.LastName, N' added to roster as Goalie (backfilled from session note)')",
    'FROM @Inserted i JOIN AspNetUsers u ON u.Id = i.UserId',
    'UNION ALL',
    "SELECT c.SessionId, NULL, GETUTCDATE(), CONCAT(u.FirstName, N' ', u.LastName, N' changed position to Goalie (backfilled from session note)')",
    'FROM @Converted c JOIN AspNetUsers u ON u.Id = c.UserId;',
    '',
    'SELECT (SELECT COUNT(*) FROM @Inserted) AS RowsInserted, (SELECT COUNT(*) FROM @Converted) AS RowsConverted;',
    'SELECT COUNT(*) AS GoalieRowsAfter FROM SessionRosters WHERE Position = 3;',
    'SELECT TOP 50 s.SessionId, s.SessionDate, u.FirstName, u.LastName, sr.TeamAssignment, sr.IsPlaying, sr.JoinedDateTime, s.Note',
    'FROM @Inserted i JOIN SessionRosters sr ON sr.SessionId = i.SessionId AND sr.UserId = i.UserId',
    'JOIN Sessions s ON s.SessionId = i.SessionId JOIN AspNetUsers u ON u.Id = i.UserId',
    'ORDER BY s.SessionDate DESC;',
    FOOTER,
  ].join('\n');
};

/** Backs up the original notes, then strips the goalie segment (D8). */
export const stripGoalieNotesSql = (analysis: Analysis): string => {
  const changes = analysis.sessions.filter((row) => row.proposedNote !== row.session.Note);

  return [
    header('03 — Strip goalie names from session notes (D8)', [
      'Run only after the front end that reads goalies from the roster is deployed and spot-checked.',
      'Original notes are copied to dbo.SessionNoteBackup_Goalies first. A note edited since the preview is left alone.',
    ]),
    'DECLARE @Notes TABLE (SessionId int NOT NULL PRIMARY KEY, OriginalNote nvarchar(max) NULL, ProposedNote nvarchar(max) NULL);',
    'DECLARE @Updated TABLE (SessionId int NOT NULL);',
    '',
    changes.length > 0
      ? insertValues(
          '@Notes',
          'SessionId, OriginalNote, ProposedNote',
          changes,
          (row) => `${row.session.SessionId}, ${str(row.session.Note)}, ${str(row.proposedNote)}`,
        )
      : '-- No notes to change.',
    '',
    "IF OBJECT_ID(N'dbo.SessionNoteBackup_Goalies', N'U') IS NULL",
    '    SELECT s.SessionId, s.Note, GETUTCDATE() AS BackedUpAt',
    '    INTO dbo.SessionNoteBackup_Goalies',
    '    FROM Sessions s WHERE s.SessionId IN (SELECT SessionId FROM @Notes);',
    'ELSE',
    '    INSERT INTO dbo.SessionNoteBackup_Goalies (SessionId, Note, BackedUpAt)',
    '    SELECT s.SessionId, s.Note, GETUTCDATE()',
    '    FROM Sessions s',
    '    WHERE s.SessionId IN (SELECT SessionId FROM @Notes)',
    '      AND NOT EXISTS (SELECT 1 FROM dbo.SessionNoteBackup_Goalies b WHERE b.SessionId = s.SessionId);',
    '',
    'UPDATE s SET Note = n.ProposedNote, UpdateDateTime = GETUTCDATE()',
    'OUTPUT inserted.SessionId INTO @Updated',
    'FROM Sessions s JOIN @Notes n ON n.SessionId = s.SessionId',
    'WHERE s.Note = n.OriginalNote;',
    '',
    'INSERT INTO ActivityLogs (SessionId, UserId, CreateDateTime, Activity)',
    "SELECT u.SessionId, NULL, GETUTCDATE(), N'Goalie names moved from the session note to the roster' FROM @Updated u;",
    '',
    'SELECT (SELECT COUNT(*) FROM @Notes) AS NotesPlanned, (SELECT COUNT(*) FROM @Updated) AS NotesUpdated,',
    '       (SELECT COUNT(*) FROM dbo.SessionNoteBackup_Goalies) AS BackupRows;',
    '-- Planned but not updated: the note changed since the preview (or this script already ran)',
    'SELECT n.SessionId, n.OriginalNote, s.Note AS CurrentNote FROM @Notes n JOIN Sessions s ON s.SessionId = n.SessionId',
    'WHERE n.SessionId NOT IN (SELECT SessionId FROM @Updated);',
    'SELECT TOP 50 b.SessionId, b.Note AS BackedUpNote, s.Note AS NewNote',
    'FROM @Updated u JOIN dbo.SessionNoteBackup_Goalies b ON b.SessionId = u.SessionId JOIN Sessions s ON s.SessionId = u.SessionId;',
    FOOTER,
  ].join('\n');
};
